'use client';

import { ScanEntry } from '@/lib/storage';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { 
  Download, 
  Zap, 
  HeartPulse, 
  Share2,
  Microscope,
  Copy,
  FileJson,
  Scale,
  FileText,
  ShieldCheck,
  Activity,
  Info
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import Image from 'next/image';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useState } from 'react';
import { type AppLanguage, uiCopy } from '@/lib/i18n';

// Production-Grade PDF Engines
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface AnalysisViewProps {
  result: ScanEntry;
  language?: AppLanguage;
}

export function AnalysisView({ result, language = 'en' }: AnalysisViewProps) {
  const { toast } = useToast();
  const [isExporting, setIsExporting] = useState(false);
  const t = uiCopy[language].analysis;

  const handleExportJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(result, null, 2));
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute("href", dataStr);
    downloadAnchorNode.setAttribute("download", `BovIntelligence_Genomic_Data_${result.id}.json`);
    document.body.appendChild(downloadAnchorNode);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
    toast({ title: "Data Exported", description: "JSON genomic record secured." });
  };

  const handleCopyText = () => {
    const text = `
BovIntelligence AI - Diagnostic Summary Report
---------------------------------------------
REPORT ID: ${result.id}
BREED: ${result.breedName}
PRECISION: ${result.confidence}
SPECIES: ${result.speciesType}
SUMMARY: ${result.diagnosticNote}
---------------------------------------------
Generated by BovIntelligence AI Genomic Vault.
    `.trim();
    navigator.clipboard.writeText(text);
    toast({ title: "Clinical Summary Copied", description: "Text snapshot secured to clipboard." });
  };

  const handleShare = async () => {
    if (typeof navigator !== 'undefined' && navigator.share) {
      try {
        await navigator.share({
          title: `BovIntelligence AI Elite Report - ${result.breedName}`,
          text: `Professional Bovine Genomic Analysis for ${result.breedName}. Record ID: ${result.id}`,
          url: window.location.href,
        });
      } catch {
        handleCopyText();
      }
    } else {
      handleCopyText();
    }
  };

  const handleDownloadPDF = async () => {
    const element = document.getElementById('report-content');
    if (!element) return;

    setIsExporting(true);
    toast({ 
      title: "Elite Export Initialized", 
      description: "Generating high-fidelity multi-page genomic documentation..." 
    });

    try {
      // Step 1: Force visibility and positioning for accurate capture
      const originalStyle = element.style.cssText;
      element.style.display = 'block';
      element.style.position = 'fixed';
      element.style.top = '0';
      element.style.left = '-10000px'; // Off-screen but active
      element.style.width = '210mm'; 
      element.style.backgroundColor = 'white';
      element.style.visibility = 'visible';

      // Brief delay to ensure DOM reflow
      await new Promise(resolve => setTimeout(resolve, 200));

      const canvas = await html2canvas(element, {
        scale: 2.5, // High resolution for professional print
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
        windowWidth: 794, // 210mm at 96dpi
      });

      // Restore original UI state
      element.style.cssText = originalStyle;

      const imgData = canvas.toDataURL('image/jpeg', 0.95);
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pdfWidth = Number(pdf.internal.pageSize.getWidth());
      const pdfHeight = Number(pdf.internal.pageSize.getHeight());
      
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const canvasHeightInPDF = (imgHeight * pdfWidth) / imgWidth;

      // Validation to prevent jsPDF errors
      if (!isFinite(pdfWidth) || !isFinite(canvasHeightInPDF) || canvasHeightInPDF <= 0) {
        throw new Error('Invalid capture dimensions. Please try again.');
      }

      let heightLeft = canvasHeightInPDF;
      let position = 0;

      // Add Page 1
      pdf.addImage(imgData, 'JPEG', 0, position, pdfWidth, canvasHeightInPDF, undefined, 'FAST');
      heightLeft -= pdfHeight;

      // Add Subsequent Pages if content overflows
      while (heightLeft > 0) {
        position = heightLeft - canvasHeightInPDF;
        pdf.addPage();
        pdf.addImage(imgData, 'JPEG', 0, position, pdfWidth, canvasHeightInPDF, undefined, 'FAST');
        heightLeft -= pdfHeight;
      }

      pdf.save(`BovIntelligence_Elite_Report_${result.id}.pdf`);
      toast({ title: "Elite Report Downloaded", description: "Professional documentation secured in local vault." });
    } catch (error: any) {
      console.error('PDF Export Error:', error);
      toast({ 
        variant: "destructive", 
        title: "Export System Failure", 
        description: error.message || "Encountered an error during high-fidelity rendering." 
      });
    } finally {
      setIsExporting(false);
    }
  };

  const notAvailable = t.notAvailable;
  const traits = {
    origin: result.traits?.origin || notAvailable,
    milkYieldEstimates: result.traits?.milkYieldEstimates || notAvailable,
    environmentalAdaptability: result.traits?.environmentalAdaptability || notAvailable,
    temperament: result.traits?.temperament || notAvailable,
    physicalCharacteristics: result.traits?.physicalCharacteristics || notAvailable,
    commonUses: result.traits?.commonUses || notAvailable,
  };
  const physiologicalAnalysis = {
    cranial: result.physiologicalAnalysis?.cranial || notAvailable,
    thoracic: result.physiologicalAnalysis?.thoracic || notAvailable,
    body: result.physiologicalAnalysis?.body || notAvailable,
  };
  const careGuide = {
    nutritionTips: result.careGuide?.nutritionTips || notAvailable,
    healthTips: result.careGuide?.healthTips || notAvailable,
  };
  const visualMarkers = result.visualMarkers?.filter(Boolean) ?? [];
  const traitSections = [
    { label: t.traits.origin, value: traits.origin, icon: Microscope, tone: 'bg-blue-50 text-blue-600' },
    { label: t.traits.production, value: traits.milkYieldEstimates, icon: Activity, tone: 'bg-emerald-50 text-emerald-600' },
    { label: t.traits.adaptability, value: traits.environmentalAdaptability, icon: Zap, tone: 'bg-amber-50 text-amber-600' },
    { label: t.traits.temperament, value: traits.temperament, icon: HeartPulse, tone: 'bg-rose-50 text-rose-600' },
    { label: t.traits.physical, value: traits.physicalCharacteristics, icon: Scale, tone: 'bg-slate-100 text-slate-700' },
    { label: t.traits.uses, value: traits.commonUses, icon: ShieldCheck, tone: 'bg-violet-50 text-violet-600' },
  ];
  const physiologySections = [
    { label: t.physiology.cranial, value: physiologicalAnalysis.cranial, icon: Microscope },
    { label: t.physiology.thoracic, value: physiologicalAnalysis.thoracic, icon: Activity },
    { label: t.physiology.body, value: physiologicalAnalysis.body, icon: Scale },
  ];

  return (
    <div className="space-y-6 pb-24 animate-in fade-in duration-700">
      
      {/* ELITE PRODUCTION REPORT (FOR PDF CAPTURE ONLY) */}
      <div id="report-content" className="bg-white p-[20mm] space-y-12 text-slate-900 hidden print:block" style={{ width: '210mm', minHeight: '297mm', fontFamily: 'serif' }}>
          
          {/* Header - Corporate Lab Style */}
          <div className="flex justify-between items-start border-b-2 border-slate-900 pb-10">
            <div className="flex items-center gap-6">
              <div className="h-16 w-16 bg-slate-900 rounded-xl flex items-center justify-center">
                <ShieldCheck className="h-12 w-12 text-white" />
              </div>
              <div>
                <h1 className="text-3xl font-bold uppercase tracking-tighter">BovIntelligence AI</h1>
                <p className="text-[11px] font-bold text-slate-500 uppercase tracking-widest">Global Genomics & Veterinary Vision Division</p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">GENOMIC RECORD ID</p>
              <p className="text-2xl font-bold">#{result.id}</p>
              <p className="text-[11px] text-slate-500 font-medium">{new Date(result.timestamp).toLocaleDateString('en-US', { day: '2-digit', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>
            </div>
          </div>

          {/* Intro Section - Clinical Presentation */}
            <div className="flex gap-12 items-start p-10 bg-slate-50 rounded-3xl border border-slate-100 shadow-sm">
            <div className="relative h-56 w-56 rounded-3xl overflow-hidden shadow-2xl flex-shrink-0 border-4 border-white">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={result.photoDataUri} alt={result.breedName} className="object-cover w-full h-full" />
            </div>
            <div className="space-y-5">
              <div className="inline-block bg-slate-900 text-white text-[10px] font-bold px-4 py-1.5 rounded-full uppercase tracking-wider">
                {result.confidence} PRECISION PROTOCOL
              </div>
              <h2 className="text-5xl font-bold text-slate-900">{result.breedName}</h2>
              <p className="text-[14px] text-slate-600 leading-relaxed font-medium italic border-l-4 border-slate-300 pl-6">
                &quot;{result.diagnosticNote}&quot;
              </p>
            </div>
          </div>

          {/* Diagnostic Content - Multi-page friendly blocks */}
          <div className="space-y-12">
            {[
              { label: 'Phylogenetic Origin & Historical Genetic Heritage', value: traits.origin, icon: Microscope },
              { label: 'Strategic Production Metrics & Genomic Yield Potential', value: traits.milkYieldEstimates, icon: Activity },
              { label: 'Ecological Resilience & Environmental Adaptability Analysis', value: traits.environmentalAdaptability, icon: Zap },
              { label: 'Ethological Behavioral Profile & Temperament Conformation', value: traits.temperament, icon: HeartPulse },
              { label: 'Elite Morphological Conformation & Phenotypic Standards', value: traits.physicalCharacteristics, icon: Scale },
              { label: 'Strategic Commercial & Traditional Utilization', value: traits.commonUses, icon: ShieldCheck }
            ].map((trait, i) => (
              <div key={i} className="space-y-5" style={{ pageBreakInside: 'avoid' }}>
                <h3 className="text-[13px] font-bold uppercase tracking-widest text-slate-800 border-b-2 border-slate-100 pb-3 flex items-center gap-4">
                  <trait.icon className="h-5 w-5 text-slate-400" /> {trait.label}
                </h3>
                <p className="text-[13px] text-slate-700 leading-[1.8] text-justify font-normal">
                  {trait.value}
                </p>
              </div>
            ))}
          </div>

          {/* Technical Care Protocols */}
          <div className="pt-12 space-y-10">
            <div className="p-10 bg-slate-900 text-white rounded-3xl shadow-xl" style={{ pageBreakInside: 'avoid' }}>
               <h3 className="text-[12px] font-bold uppercase tracking-widest mb-6 border-b border-white/20 pb-3">Elite Nutritional Optimization Protocol</h3>
               <p className="text-[13px] text-slate-300 leading-[1.8] text-justify">{careGuide.nutritionTips}</p>
            </div>
            <div className="p-10 bg-white border-2 border-slate-100 rounded-3xl shadow-sm" style={{ pageBreakInside: 'avoid' }}>
               <h3 className="text-[12px] font-bold uppercase tracking-widest mb-6 text-slate-900 border-b border-slate-200 pb-3">Clinical Health Maintenance & Preventive Care</h3>
               <p className="text-[13px] text-slate-600 leading-[1.8] text-justify">{careGuide.healthTips}</p>
            </div>
          </div>

          {/* Footer */}
          <div className="pt-16 text-center border-t border-slate-100">
            <p className="text-[10px] text-slate-400 font-bold uppercase tracking-[0.6em]">
              CONFIDENTIAL | BOVINTELLIGENCE AI GENOMIC VAULT | GLOBAL LIVESTOCK DIAGNOSTICS
            </p>
          </div>
      </div>
      
      {/* VISUAL UI FOR SCREEN DISPLAY */}
      <div className="space-y-4">
        <Card className="overflow-hidden rounded-lg border-slate-200 shadow-sm relative bg-slate-950">
          <div className="relative min-h-[320px] w-full">
            <Image src={result.photoDataUri} alt={result.breedName} fill className="object-cover" priority />
            <div className="absolute inset-0 bg-gradient-to-t from-[#0F172A] via-[#0F172A]/35 to-transparent" />
            <div className="absolute left-5 right-5 top-5 flex items-start justify-between gap-3">
              <Badge className="rounded-md border-none bg-white/90 px-3 py-1 text-[9px] font-black uppercase text-slate-900 shadow-sm">
                {result.speciesType || 'Bovine'}
              </Badge>
              <Badge className="max-w-[136px] whitespace-normal rounded-md border-none bg-accent px-3 py-1.5 text-center text-[9px] font-black uppercase leading-tight text-white shadow-sm">
                {result.confidence || 'N/A'} {t.precision}
              </Badge>
            </div>
            <div className="absolute bottom-6 left-6 right-6 space-y-3">
              <p className="text-[10px] font-black text-accent uppercase tracking-widest">{t.masterDiagnostic}</p>
              <h2 className="text-4xl font-headline font-bold text-white leading-tight break-words">{result.breedName}</h2>
              <div className="flex flex-wrap gap-2">
                <span className="rounded-md bg-white/15 px-3 py-1 text-[10px] font-bold uppercase text-white backdrop-blur-md">
                  {result.detectedStatus || 'Success'}
                </span>
                <span className="rounded-md bg-white/15 px-3 py-1 text-[10px] font-bold uppercase text-white backdrop-blur-md">
                  #{result.id}
                </span>
              </div>
            </div>
          </div>
        </Card>

        <Card className="p-4 rounded-lg border-slate-200 shadow-sm space-y-4 bg-white">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-accent/10 flex items-center justify-center">
              <Info className="h-5 w-5 text-accent" />
            </div>
            <div>
              <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{t.diagnosticSummary}</p>
              <h3 className="font-bold text-lg text-[#0F172A]">{t.breedDetails}</h3>
            </div>
          </div>
          <p className="text-sm text-slate-600 leading-7 whitespace-pre-line">
            {result.diagnosticNote || notAvailable}
          </p>
        </Card>

        {visualMarkers.length > 0 && (
          <Card className="p-4 rounded-lg border-slate-200 shadow-sm space-y-4 bg-white">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-xl bg-amber-50 flex items-center justify-center">
                <Zap className="h-5 w-5 text-amber-600" />
              </div>
              <h3 className="font-bold text-lg text-[#0F172A]">{t.visualEvidence}</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              {visualMarkers.map((marker, index) => (
                <span key={`${marker}-${index}`} className="rounded-md bg-slate-100 px-3 py-2 text-[11px] font-bold leading-snug text-slate-700">
                  {marker}
                </span>
              ))}
            </div>
          </Card>
        )}

        <div className="space-y-3">
          <div className="px-1">
            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{t.completeProfile}</p>
          </div>
          {traitSections.map((section) => (
            <Card key={section.label} className="p-4 rounded-lg border-slate-200 shadow-sm space-y-4 bg-white">
              <div className="flex items-center gap-3">
                <div className={`h-10 w-10 rounded-xl flex items-center justify-center ${section.tone}`}>
                  <section.icon className="h-5 w-5" />
                </div>
                <h3 className="font-bold text-lg text-[#0F172A] leading-tight">{section.label}</h3>
              </div>
              <p className="text-sm text-slate-600 leading-7 whitespace-pre-line">
                {section.value}
              </p>
            </Card>
          ))}
        </div>

        <div className="space-y-3">
          <div className="px-1">
            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{t.physiological}</p>
          </div>
          {physiologySections.map((section) => (
            <Card key={section.label} className="p-4 rounded-lg border-slate-200 shadow-sm space-y-4 bg-white">
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-xl bg-slate-100 flex items-center justify-center">
                  <section.icon className="h-5 w-5 text-slate-700" />
                </div>
                <h3 className="font-bold text-lg text-[#0F172A] leading-tight">{section.label}</h3>
              </div>
              <p className="text-sm text-slate-600 leading-7 whitespace-pre-line">
                {section.value}
              </p>
            </Card>
          ))}
        </div>

        <Card className="p-4 rounded-lg border-none shadow-sm space-y-4 bg-slate-900 text-white">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-white/10 flex items-center justify-center">
              <HeartPulse className="h-5 w-5 text-accent" />
            </div>
            <h3 className="font-bold text-lg leading-tight">{t.nutrition}</h3>
          </div>
          <p className="text-sm text-slate-300 leading-7 whitespace-pre-line">
            {careGuide.nutritionTips}
          </p>
        </Card>

        <Card className="p-4 rounded-lg border-slate-200 shadow-sm space-y-4 bg-white">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-rose-50 flex items-center justify-center">
              <ShieldCheck className="h-5 w-5 text-rose-600" />
            </div>
            <h3 className="font-bold text-lg text-[#0F172A] leading-tight">{t.health}</h3>
          </div>
          <p className="text-sm text-slate-600 leading-7 whitespace-pre-line">
            {careGuide.healthTips}
          </p>
        </Card>

        <Card className="p-4 rounded-lg border-slate-200 shadow-sm space-y-4 bg-white">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-slate-100 flex items-center justify-center">
              <FileText className="h-5 w-5 text-slate-700" />
            </div>
            <h3 className="font-bold text-lg text-[#0F172A] leading-tight">{t.similarBreed}</h3>
          </div>
          <p className="text-sm text-slate-600 leading-7 whitespace-pre-line">
            {result.negativeConstraints || notAvailable}
          </p>
        </Card>
      </div>
      
      {/* PROFESSIONAL ACTION BAR */}
      <div className="flex gap-3 sticky bottom-20 z-50">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button disabled={isExporting} className="flex-1 rounded-md h-12 bg-slate-900 text-white font-bold text-[11px] uppercase tracking-widest gap-3 shadow-lg hover:bg-slate-800 transition-all active:scale-95">
              <Download className="h-6 w-6" /> {isExporting ? t.processing : t.exportReport}
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-72 rounded-lg p-3 bg-white/95 backdrop-blur-xl border-slate-100 shadow-xl">
            <DropdownMenuItem 
              onClick={(e) => { e.preventDefault(); handleDownloadPDF(); }} 
              className="flex gap-4 py-3 rounded-md cursor-pointer hover:bg-slate-50 focus:bg-slate-50 transition-colors"
            >
              <FileText className="h-6 w-6 text-accent" />
              <div className="flex flex-col">
                <span className="text-[11px] font-black uppercase tracking-wider">{t.pdf}</span>
                <span className="text-[9px] text-slate-400 font-bold">{t.pdfHint}</span>
              </div>
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleCopyText} className="flex gap-4 py-3 rounded-md cursor-pointer hover:bg-slate-50 focus:bg-slate-50 transition-colors">
              <Copy className="h-6 w-6 text-slate-500" />
              <div className="flex flex-col">
                <span className="text-[11px] font-black uppercase tracking-wider">{t.copy}</span>
                <span className="text-[9px] text-slate-400 font-bold">{t.copyHint}</span>
              </div>
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleExportJSON} className="flex gap-4 py-3 rounded-md cursor-pointer hover:bg-slate-50 focus:bg-slate-50 transition-colors">
              <FileJson className="h-6 w-6 text-slate-500" />
              <div className="flex flex-col">
                <span className="text-[11px] font-black uppercase tracking-wider">{t.json}</span>
                <span className="text-[9px] text-slate-400 font-bold">{t.jsonHint}</span>
              </div>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>

        <Button onClick={handleShare} variant="outline" className="h-12 w-12 rounded-md border-white bg-white/90 backdrop-blur-md flex items-center justify-center shadow-lg hover:bg-white transition-all active:scale-90">
          <Share2 className="h-6 w-6 text-slate-700" />
        </Button>
      </div>

    </div>
  );
}
